"""
Medical Term Mapper
===================

Generates a mapping dictionary from scientific medical terms to patient-friendly layman terms.
This dictionary will be used to normalize the Knowledge Base and Question Engine.
"""

# Dictionary of Scientific -> Layman terms
# Based on common medical noise found in the dataset
SCIENTIFIC_TO_LAYMAN = {
    "dyspnea": "shortness of breath",
    "myalgia": "muscle pain",
    "arthralgia": "joint pain",
    "rhinorrhea": "runny nose",
    "edema": "swelling",
    "erythema": "redness",
    "pruritus": "itching",
    "syncope": "fainting",
    "palpitations": "heart racing or skipping beats",
    "tachycardia": "fast heart rate",
    "bradycardia": "slow heart rate",
    "hypertension": "high blood pressure",
    "hypotension": "low blood pressure",
    "emesis": "vomiting",
    "nausea": "feeling sick to your stomach",
    "diarrhea": "loose stools",
    "constipation": "difficulty passing stools",
    "insomnia": "trouble sleeping",
    "fatigue": "tiredness",
    "malaise": "general feeling of being unwell",
    "vertigo": "dizziness or spinning sensation",
    "tinnitus": "ringing in the ears",
    "epistaxis": "nosebleed",
    "hemoptysis": "coughing up blood",
    "hematemesis": "vomiting blood",
    "hematochezia": "blood in stool",
    "melena": "black tarry stools",
    "dysuria": "painful urination",
    "hematuria": "blood in urine",
    "polyuria": "frequent urination",
    "nocturia": "waking up at night to urinate",
    "polydipsia": "excessive thirst",
    "polyphagia": "excessive hunger",
    "anorexia": "loss of appetite",
    "weight loss": "unexplained weight loss",
    "weight gain": "unexplained weight gain",
    "febril": "feverish",
    "pyrexia": "fever",
    "chills": "shivering",
    "diaphoresis": "excessive sweating",
    "cyanosis": "bluish skin complication",
    "pallor": "paleness",
    "jaundice": "yellowing of skin/eyes",
    "ascites": "abdominal swelling",
    "hepatomegaly": "enlarged liver",
    "splenomegaly": "enlarged spleen",
    "lymphadenopathy": "swollen lymph nodes",
    "rash": "skin rash",
    "lesion": "skin sore or spot",
    "ulcer": "open sore",
    "abscess": "pus-filled lump",
    "cyst": "fluid-filled lump",
    "tumor": "lump or growth",
    "mass": "lump",
    "laceration": "cut",
    "abrasion": "scrape",
    "contusion": "bruise",
    "fracture": "broken bone",
    "dislocation": "joint out of place",
    "sprain": "ligament injury",
    "strain": "muscle injury",
    "burn": "burn injury",
    "bite": "animal or insect bite",
    "sting": "insect sting",
    "foreign body": "object stuck in body",
    "poisoning": "swallowing poison",
    "overdose": "taking too much medicine",
    "suicide attempt": "hurting yourself on purpose",
    "assault": "being attacked",
    "abuse": "being mistreated",
    "neglect": "being neglected",
    "rape": "sexual assault",
    "homicide": "being killed",
    "accident": "accident",
    "incident": "event",
    "complaint": "problem",
    "symptom": "feeling",
    "sign": "observable change",
    "diagnosis": "condition",
    "prognosis": "outcome",
    "treatment": "care",
    "medication": "medicine",
    "drug": "medicine",
    "surgery": "operation",
    "hospitalization": "staying in hospital",
    "consultation": "seeing a doctor",
    "referral": "being sent to a specialist",
    "follow-up": "check-up",
    "thyroid cartilage": "adam's apple (throat)",
    "palace": "roof of mouth (palate)",
    "pharynx": "throat",
    "larynx": "voice box",
    "trachea": "windpipe",
    "esophagus": "food pipe",
    "stomach": "belly",
    "intestine": "gut",
    "colon": "large bowel",
    "rectum": "back passage",
    "anus": "bottom",
    "liver": "liver",
    "gallbladder": "gallbladder",
    "pancreas": "pancreas",
    "spleen": "spleen",
    "kidney": "kidney",
    "bladder": "urine bag",
    "urethra": "urine tube",
    "uterus": "womb",
    "ovary": "egg sac",
    "fallopian tube": "egg tube",
    "vagina": "birth canal",
    "testicle": "ball",
    "scrotum": "ball sack",
    "prostate": "prostate gland",
    "penis": "penis",
    "brain": "brain",  
    "spinal cord": "spine nerve",
    "nerve": "nerve",
    "muscle": "muscle",
    "bone": "bone",
    "joint": "joint",
    "ligament": "ligament",
    "tendon": "tendon",
    "skin": "skin",
    "hair": "hair",
    "nail": "nail",
    "eye": "eye",
    "ear": "ear",
    "nose": "nose",
    "mouth": "mouth",
    "tooth": "tooth",
    "gum": "gum",
    "tongue": "tongue",
    "lip": "lip",
    "cheek": "cheek",
    "chin": "chin",
    "neck": "neck",
    "shoulder": "shoulder",
    "arm": "arm",
    "elbow": "elbow",
    "forearm": "lower arm",
    "wrist": "wrist",
    "hand": "hand",
    "finger": "finger",
    "thumb": "thumb",
    "chest": "chest",
    "breast": "breast",
    "nipple": "nipple",
    "abdomen": "tummy",
    "umbilicus": "belly button",
    "back": "back",
    "spine": "backbone",
    "hip": "hip",
    "leg": "leg",
    "thigh": "upper leg",
    "knee": "knee",
    "shin": "shin",
    "calf": "calf",
    "ankle": "ankle",
    "foot": "foot",
    "toe": "toe",
    "heel": "heel",
    "underweight": "being very thin",
    "overweight": "being heavy",
    "obesity": "being very heavy"
}

import json
from pathlib import Path

def save_mapping():
    path = Path(__file__).parent / "knowledge" / "term_mapping.json"
    print(f"Saving mapping to {path}...")
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(SCIENTIFIC_TO_LAYMAN, f, indent=2)
    print("✅ Mapping saved.")

if __name__ == "__main__":
    save_mapping()
